name: "Create Pull"
description: "An action to create a pull create inside orignal Repo"
inputs:
  upstream_owner:
    description: Original owner of the repo.
    required: true
  forked_branch:
    description: Your branch which you are going to create a PR against.
    required: true
  token:
    description: Your Github Token
    required: true
  upstream_repo:
    description: The name of your repo
    required: true
  upstream_branch:
    description: The default branch of owner. This would be the one which you are going to create a pull request against
    required: true
runs:
  using: node12
  main: dist/index.js
