name: "GitSlicePull"
description: "An action to pull changes into a git-sliced repo"
inputs:
  slice_git_username:
    description: Username of the git user with access to sliced repo
    required: false
  upstream_git_username:
    description: Username of the git user with access to upstream repo
    required: false
  upstream_git_email:
    description: Email of git user with access to upstream repo
    required: true
  slice_git_token:
    description: Github access token for git-sliced repo
    required: true
  upstream_git_token:
    description: Git access token for upstream repo
    required: false
  custom_commit_message:
    description: Git commit message for the upstream repo
    required: true 
  slice_branch_to_push:
    description: Git branch that should be pushed to the client
    required: true  
  push_pr: 
    description: Should pull request be created on the client side
    required: false
  overide_previous_push:
    description: Overides previous push (force push) if set to true
    required: false  
runs:
  using: node12
  main: dist/index.js