name: 'GitSlicePush'
description: 'An action to push changes into a git-sliced repo'
inputs:
  slice_git_username:
    description: Username of the git user with access to sliced repo
    required: false
  upstream_git_username:
    description: Username of the git user with access to upstream repo
    required: false
  upstream_git_email:
    description: Email of git user with access to upstream repo
    required: false
  slice_default_branch:
    description: Primary branch on the git-sliced repo for all pull requests
    required: true
  slice_git_token:
    description: Github access token for git-sliced repo
    required: false
  upstream_git_token:
    description: Git access token for upstream repo
    required: false
  custom_commit_message:
    description: Git commit message for the upstream repo
    required: true
  slice_branch_to_push:
    description: Git branch that should be pushed to the client
    required: true
  no_cache:
    description: 'Disable cache? true/false'
    required: false
  push_pr:
    description: Should pull request be created on the client side
    required: false
  overide_previous_push:
    description: Overides previous push (force push) if set to true
    required: false
  rebase_branch:
    description: Controls whether rebase should be used to update branch instead of the default merge
    required: false
    default: 'false'
  is_open_source:
    description: Boolean marker for open source project
    required: false
  is_draft:
    description: Boolean marker for creating a draft PR or not (only works for first push, defaults to false)
    required: false
runs:
  using: node12
  main: dist/index.js
