name: "Create Pull"
description: "An action to create a pull create inside orignal Repo"
inputs:
  upstream_owner:
    description: Orignal ower of the repo.
    required: true
  token:
    description: Your Github Token
    required: true
  upstream_repo:
    description: The name of your repo
    required: true
runs:
  using: node12
  main: dist/index.js
