name: 'GitSlicePull'
description: 'An action to pull changes into a git-sliced repo'
inputs:
  slice_git_username:
    description: Username of the Git User with access to sliced repo
    required: false
  upstream_git_username:
    description: Username of the Git User with access to upstream repo
    required: false
  upstream_git_email:
    description: Email of Git User with access to upstream repo
    required: true
  slice_default_branch:
    description: Primary branch on the git-sliced repo for all pull requests
    required: true
  slice_git_token:
    description: Github Access Token for git-sliced repo
    required: false
  upstream_git_token:
    description: Github Access Token for upstream repo
    required: false
  is_open_source:
    description: Boolean marker for open source project
    required: false
  branch_to_pull:
    description: Branch to pull if different from main
    required: false
  gitslice_pull_url:
    description: URL endpoint of the GitSlice Pull API
    required: false
runs:
  using: node12
  main: dist/index.js
